#https://github.com/deepshig/rabbitmq-docker
version: "3.2"

# list of containers to be run
services:
  # produces container builds the producer image
  # and produces message to the queue
  
  consumer:
    build: consumer
    restart: always
    ports:
      - "1001:80"  

    #depends_on:
    #    - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer

    networks: 
    - default

volumes:
    rabbit_mqdata:
      driver: local

networks:
  default:
    external:
      name: queue_network # Create Network --> docker network create queue_network      