# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employeeupdateform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 477)
        self.ulabel = QtWidgets.QLabel(Form)
        self.ulabel.setGeometry(QtCore.QRect(40, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ulabel.setFont(font)
        self.ulabel.setObjectName("ulabel")
        self.tlabel = QtWidgets.QLabel(Form)
        self.tlabel.setGeometry(QtCore.QRect(270, 20, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tlabel.setFont(font)
        self.tlabel.setObjectName("tlabel")
        self.tcombo = QtWidgets.QComboBox(Form)
        self.tcombo.setGeometry(QtCore.QRect(350, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tcombo.setFont(font)
        self.tcombo.setObjectName("tcombo")
        self.emplabel = QtWidgets.QLabel(Form)
        self.emplabel.setGeometry(QtCore.QRect(20, 120, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emplabel.setFont(font)
        self.emplabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emplabel.setObjectName("emplabel")
        self.datalist = QtWidgets.QListWidget(Form)
        self.datalist.setGeometry(QtCore.QRect(60, 160, 421, 301))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datalist.setFont(font)
        self.datalist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datalist.setObjectName("datalist")
        self.ptext = QtWidgets.QLineEdit(Form)
        self.ptext.setGeometry(QtCore.QRect(150, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.ptext.setFont(font)
        self.ptext.setObjectName("ptext")
        self.savebutton = QtWidgets.QPushButton(Form)
        self.savebutton.setGeometry(QtCore.QRect(270, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.savebutton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebutton.setIcon(icon)
        self.savebutton.setIconSize(QtCore.QSize(16, 16))
        self.savebutton.setObjectName("savebutton")
        self.plabel = QtWidgets.QLabel(Form)
        self.plabel.setGeometry(QtCore.QRect(40, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plabel.setFont(font)
        self.plabel.setObjectName("plabel")
        self.closebutton = QtWidgets.QPushButton(Form)
        self.closebutton.setGeometry(QtCore.QRect(390, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closebutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon1)
        self.closebutton.setIconSize(QtCore.QSize(16, 16))
        self.closebutton.setObjectName("closebutton")
        self.utext = QtWidgets.QLineEdit(Form)
        self.utext.setEnabled(False)
        self.utext.setGeometry(QtCore.QRect(150, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.utext.setFont(font)
        self.utext.setObjectName("utext")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Employee Form: update"))
        self.ulabel.setText(_translate("Form", "username"))
        self.tlabel.setText(_translate("Form", "Type"))
        self.emplabel.setText(_translate("Form", "Employee List (Double Click for Employee Delete)"))
        self.savebutton.setText(_translate("Form", "Save"))
        self.savebutton.setShortcut(_translate("Form", "Enter"))
        self.plabel.setText(_translate("Form", "password"))
        self.closebutton.setText(_translate("Form", "Close"))
