# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menusform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pqrybutton = QtWidgets.QPushButton(self.centralwidget)
        self.pqrybutton.setGeometry(QtCore.QRect(230, 130, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pqrybutton.setFont(font)
        self.pqrybutton.setObjectName("pqrybutton")
        self.stinsertbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stinsertbutton.setGeometry(QtCore.QRect(60, 170, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stinsertbutton.setFont(font)
        self.stinsertbutton.setObjectName("stinsertbutton")
        self.pinsertbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pinsertbutton.setGeometry(QtCore.QRect(60, 130, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pinsertbutton.setFont(font)
        self.pinsertbutton.setObjectName("pinsertbutton")
        self.stqrybutton = QtWidgets.QPushButton(self.centralwidget)
        self.stqrybutton.setGeometry(QtCore.QRect(230, 170, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stqrybutton.setFont(font)
        self.stqrybutton.setObjectName("stqrybutton")
        self.empqrybutton = QtWidgets.QPushButton(self.centralwidget)
        self.empqrybutton.setEnabled(True)
        self.empqrybutton.setGeometry(QtCore.QRect(230, 90, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.empqrybutton.setFont(font)
        self.empqrybutton.setObjectName("empqrybutton")
        self.closebutton = QtWidgets.QPushButton(self.centralwidget)
        self.closebutton.setGeometry(QtCore.QRect(360, 180, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closebutton.setFont(font)
        self.closebutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon)
        self.closebutton.setIconSize(QtCore.QSize(30, 30))
        self.closebutton.setObjectName("closebutton")
        self.datalabel = QtWidgets.QLabel(self.centralwidget)
        self.datalabel.setGeometry(QtCore.QRect(60, 50, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datalabel.setFont(font)
        self.datalabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datalabel.setObjectName("datalabel")
        self.qrylabel = QtWidgets.QLabel(self.centralwidget)
        self.qrylabel.setGeometry(QtCore.QRect(231, 50, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.qrylabel.setFont(font)
        self.qrylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qrylabel.setObjectName("qrylabel")
        self.vline = QtWidgets.QFrame(self.centralwidget)
        self.vline.setGeometry(QtCore.QRect(190, -20, 20, 350))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.vline.setFont(font)
        self.vline.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline.setObjectName("vline")
        self.empinsertbutton = QtWidgets.QPushButton(self.centralwidget)
        self.empinsertbutton.setEnabled(True)
        self.empinsertbutton.setGeometry(QtCore.QRect(60, 90, 111, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.empinsertbutton.setFont(font)
        self.empinsertbutton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.empinsertbutton.setObjectName("empinsertbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 26))
        self.menubar.setObjectName("menubar")
        self.menuupdate = QtWidgets.QMenu(self.menubar)
        self.menuupdate.setObjectName("menuupdate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionproduct = QtWidgets.QAction(MainWindow)
        self.actionproduct.setObjectName("actionproduct")
        self.actionmember = QtWidgets.QAction(MainWindow)
        self.actionmember.setObjectName("actionmember")
        self.actionstockin = QtWidgets.QAction(MainWindow)
        self.actionstockin.setObjectName("actionstockin")
        self.actionemployee = QtWidgets.QAction(MainWindow)
        self.actionemployee.setObjectName("actionemployee")
        self.menuupdate.addAction(self.actionemployee)
        self.menuupdate.addAction(self.actionproduct)
        self.menubar.addAction(self.menuupdate.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main menu"))
        self.pqrybutton.setText(_translate("MainWindow", "product"))
        self.stinsertbutton.setText(_translate("MainWindow", "stock in"))
        self.pinsertbutton.setText(_translate("MainWindow", "product"))
        self.stqrybutton.setText(_translate("MainWindow", "stock in"))
        self.empqrybutton.setText(_translate("MainWindow", "employee"))
        self.datalabel.setText(_translate("MainWindow", "DATA"))
        self.qrylabel.setText(_translate("MainWindow", "QUERY"))
        self.empinsertbutton.setText(_translate("MainWindow", "employee"))
        self.menuupdate.setTitle(_translate("MainWindow", "update"))
        self.actionproduct.setText(_translate("MainWindow", "product"))
        self.actionmember.setText(_translate("MainWindow", "member"))
        self.actionstockin.setText(_translate("MainWindow", "stockin"))
        self.actionemployee.setText(_translate("MainWindow", "employee"))
