# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'productinsertform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 340)
        self.ilabel = QtWidgets.QLabel(Form)
        self.ilabel.setGeometry(QtCore.QRect(30, 30, 50, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.ilabel.setFont(font)
        self.ilabel.setObjectName("ilabel")
        self.alabel = QtWidgets.QLabel(Form)
        self.alabel.setGeometry(QtCore.QRect(30, 130, 50, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.alabel.setFont(font)
        self.alabel.setObjectName("alabel")
        self.clabel = QtWidgets.QLabel(Form)
        self.clabel.setGeometry(QtCore.QRect(30, 180, 50, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.clabel.setFont(font)
        self.clabel.setObjectName("clabel")
        self.nlabel = QtWidgets.QLabel(Form)
        self.nlabel.setGeometry(QtCore.QRect(30, 80, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.nlabel.setFont(font)
        self.nlabel.setObjectName("nlabel")
        self.closebutton = QtWidgets.QPushButton(Form)
        self.closebutton.setGeometry(QtCore.QRect(410, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.closebutton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon)
        self.closebutton.setIconSize(QtCore.QSize(16, 16))
        self.closebutton.setObjectName("closebutton")
        self.savebutton = QtWidgets.QPushButton(Form)
        self.savebutton.setGeometry(QtCore.QRect(280, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.savebutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebutton.setIcon(icon1)
        self.savebutton.setIconSize(QtCore.QSize(16, 16))
        self.savebutton.setObjectName("savebutton")
        self.piclabel = QtWidgets.QLabel(Form)
        self.piclabel.setGeometry(QtCore.QRect(280, 30, 231, 211))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.piclabel.setFont(font)
        self.piclabel.setStyleSheet("background-color:rgb(227, 227, 227);")
        self.piclabel.setScaledContents(True)
        self.piclabel.setAlignment(QtCore.Qt.AlignCenter)
        self.piclabel.setObjectName("piclabel")
        self.browsebutton = QtWidgets.QPushButton(Form)
        self.browsebutton.setGeometry(QtCore.QRect(160, 260, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.browsebutton.setFont(font)
        self.browsebutton.setObjectName("browsebutton")
        self.picnamelabel = QtWidgets.QLabel(Form)
        self.picnamelabel.setGeometry(QtCore.QRect(30, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.picnamelabel.setFont(font)
        self.picnamelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.picnamelabel.setObjectName("picnamelabel")
        self.ntext = QtWidgets.QLineEdit(Form)
        self.ntext.setGeometry(QtCore.QRect(90, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.ntext.setFont(font)
        self.ntext.setObjectName("ntext")
        self.itext = QtWidgets.QLineEdit(Form)
        self.itext.setEnabled(False)
        self.itext.setGeometry(QtCore.QRect(90, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.itext.setFont(font)
        self.itext.setObjectName("itext")
        self.qtext = QtWidgets.QLineEdit(Form)
        self.qtext.setGeometry(QtCore.QRect(90, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.qtext.setFont(font)
        self.qtext.setObjectName("qtext")
        self.ctext = QtWidgets.QLineEdit(Form)
        self.ctext.setGeometry(QtCore.QRect(90, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.ctext.setFont(font)
        self.ctext.setObjectName("ctext")
        self.pictext = QtWidgets.QLineEdit(Form)
        self.pictext.setEnabled(False)
        self.pictext.setGeometry(QtCore.QRect(30, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.pictext.setFont(font)
        self.pictext.setObjectName("pictext")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Product Form: insert"))
        self.ilabel.setText(_translate("Form", "ID"))
        self.alabel.setText(_translate("Form", "Q\'ty"))
        self.clabel.setText(_translate("Form", "Cost"))
        self.nlabel.setText(_translate("Form", "Name"))
        self.closebutton.setText(_translate("Form", "Close"))
        self.savebutton.setText(_translate("Form", "Save"))
        self.savebutton.setShortcut(_translate("Form", "Enter"))
        self.piclabel.setText(_translate("Form", "Picture File"))
        self.browsebutton.setText(_translate("Form", "Browse"))
        self.picnamelabel.setText(_translate("Form", "Picture File Name"))
