# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockininsertform.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 335)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.savebutton = QtWidgets.QPushButton(Form)
        self.savebutton.setGeometry(QtCore.QRect(480, 270, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.savebutton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebutton.setIcon(icon)
        self.savebutton.setIconSize(QtCore.QSize(16, 16))
        self.savebutton.setObjectName("savebutton")
        self.closebutton = QtWidgets.QPushButton(Form)
        self.closebutton.setGeometry(QtCore.QRect(620, 270, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.closebutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon1)
        self.closebutton.setIconSize(QtCore.QSize(16, 16))
        self.closebutton.setObjectName("closebutton")
        self.qlabel = QtWidgets.QLabel(Form)
        self.qlabel.setGeometry(QtCore.QRect(30, 260, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.qlabel.setFont(font)
        self.qlabel.setWordWrap(True)
        self.qlabel.setObjectName("qlabel")
        self.datalist = QtWidgets.QListWidget(Form)
        self.datalist.setGeometry(QtCore.QRect(480, 50, 261, 211))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datalist.setFont(font)
        self.datalist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datalist.setObjectName("datalist")
        self.datalabel = QtWidgets.QLabel(Form)
        self.datalabel.setGeometry(QtCore.QRect(480, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datalabel.setFont(font)
        self.datalabel.setObjectName("datalabel")
        self.vline2 = QtWidgets.QFrame(Form)
        self.vline2.setGeometry(QtCore.QRect(20, 210, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.vline2.setFont(font)
        self.vline2.setFrameShape(QtWidgets.QFrame.HLine)
        self.vline2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline2.setObjectName("vline2")
        self.qtext = QtWidgets.QLineEdit(Form)
        self.qtext.setGeometry(QtCore.QRect(120, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.qtext.setFont(font)
        self.qtext.setObjectName("qtext")
        self.costtext = QtWidgets.QLineEdit(Form)
        self.costtext.setGeometry(QtCore.QRect(340, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.costtext.setFont(font)
        self.costtext.setObjectName("costtext")
        self.costlabel = QtWidgets.QLabel(Form)
        self.costlabel.setGeometry(QtCore.QRect(250, 260, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.costlabel.setFont(font)
        self.costlabel.setWordWrap(True)
        self.costlabel.setObjectName("costlabel")
        self.datelabel = QtWidgets.QLabel(Form)
        self.datelabel.setGeometry(QtCore.QRect(240, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.datelabel.setFont(font)
        self.datelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.datelabel.setWordWrap(False)
        self.datelabel.setObjectName("datelabel")
        self.datetext = QtWidgets.QDateEdit(Form)
        self.datetext.setGeometry(QtCore.QRect(310, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.datetext.setFont(font)
        self.datetext.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.datetext.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 9, 1), QtCore.QTime(0, 0, 0)))
        self.datetext.setTimeSpec(QtCore.Qt.LocalTime)
        self.datetext.setObjectName("datetext")
        self.pclabel = QtWidgets.QLabel(Form)
        self.pclabel.setGeometry(QtCore.QRect(240, 170, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pclabel.setFont(font)
        self.pclabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pclabel.setObjectName("pclabel")
        self.plabel = QtWidgets.QLabel(Form)
        self.plabel.setGeometry(QtCore.QRect(20, 60, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.plabel.setFont(font)
        self.plabel.setAlignment(QtCore.Qt.AlignCenter)
        self.plabel.setObjectName("plabel")
        self.pqlabel = QtWidgets.QLabel(Form)
        self.pqlabel.setGeometry(QtCore.QRect(30, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pqlabel.setFont(font)
        self.pqlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pqlabel.setObjectName("pqlabel")
        self.pitext = QtWidgets.QLineEdit(Form)
        self.pitext.setEnabled(False)
        self.pitext.setGeometry(QtCore.QRect(100, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.pitext.setFont(font)
        self.pitext.setObjectName("pitext")
        self.pctext = QtWidgets.QLineEdit(Form)
        self.pctext.setEnabled(False)
        self.pctext.setGeometry(QtCore.QRect(310, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.pctext.setFont(font)
        self.pctext.setObjectName("pctext")
        self.pnlabel = QtWidgets.QLabel(Form)
        self.pnlabel.setGeometry(QtCore.QRect(240, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pnlabel.setFont(font)
        self.pnlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pnlabel.setObjectName("pnlabel")
        self.pntext = QtWidgets.QLineEdit(Form)
        self.pntext.setEnabled(False)
        self.pntext.setGeometry(QtCore.QRect(310, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.pntext.setFont(font)
        self.pntext.setObjectName("pntext")
        self.pilabel = QtWidgets.QLabel(Form)
        self.pilabel.setGeometry(QtCore.QRect(30, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pilabel.setFont(font)
        self.pilabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pilabel.setObjectName("pilabel")
        self.vline1 = QtWidgets.QFrame(Form)
        self.vline1.setGeometry(QtCore.QRect(20, 90, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.vline1.setFont(font)
        self.vline1.setFrameShape(QtWidgets.QFrame.HLine)
        self.vline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.pqtext = QtWidgets.QLineEdit(Form)
        self.pqtext.setEnabled(False)
        self.pqtext.setGeometry(QtCore.QRect(100, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.pqtext.setFont(font)
        self.pqtext.setObjectName("pqtext")
        self.emptext = QtWidgets.QLineEdit(Form)
        self.emptext.setEnabled(False)
        self.emptext.setGeometry(QtCore.QRect(140, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.emptext.setFont(font)
        self.emptext.setObjectName("emptext")
        self.emplabel = QtWidgets.QLabel(Form)
        self.emplabel.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emplabel.setFont(font)
        self.emplabel.setObjectName("emplabel")
        self.stlabel = QtWidgets.QLabel(Form)
        self.stlabel.setGeometry(QtCore.QRect(20, 220, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.stlabel.setFont(font)
        self.stlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stlabel.setObjectName("stlabel")
        self.vline2_2 = QtWidgets.QFrame(Form)
        self.vline2_2.setGeometry(QtCore.QRect(20, 250, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.vline2_2.setFont(font)
        self.vline2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.vline2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline2_2.setObjectName("vline2_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Stock in Form: insert"))
        self.savebutton.setText(_translate("Form", "Save"))
        self.savebutton.setShortcut(_translate("Form", "Enter"))
        self.closebutton.setText(_translate("Form", "Close"))
        self.qlabel.setText(_translate("Form", "Stock In Q\'ty"))
        self.datalabel.setText(_translate("Form", "Product List"))
        self.costlabel.setText(_translate("Form", "Stock In Cost"))
        self.datelabel.setText(_translate("Form", "Date"))
        self.datetext.setDisplayFormat(_translate("Form", "dd/MM/yyyy"))
        self.pclabel.setText(_translate("Form", "Cost"))
        self.plabel.setText(_translate("Form", "Product Information"))
        self.pqlabel.setText(_translate("Form", "Q\'ty"))
        self.pnlabel.setText(_translate("Form", "Name"))
        self.pilabel.setText(_translate("Form", "ID"))
        self.emplabel.setText(_translate("Form", "Employee ID"))
        self.stlabel.setText(_translate("Form", "Stock In Information"))
