version: '3'

services:
  register:
    container_name: register_gateway
    build: python/
    restart: always
    ports:
      - "7001:80"  
    environment: 
      VIRTUAL_HOST: serviceRegister.dev.docker
      VIRTUAL_PORT: 7001

networks:
  default:
    external:
      name: service_network # Create Network --> docker network create service_network