name: Build and Push OCI CLI Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 3'  # Tuesday@17h30 Pacific = Wednesday@00h30 UTC
  push:
    branches: [ "main" ]
    paths:
      - 'OracleCloudInfrastructuree/oci-cli/*'
      - '.github/workflows/build-and-push-oci-cli-image.yml'
  pull_request:
    paths:
      - 'OracleCloudInfrastructuree/oci-cli/*'
      - '.github/workflows/build-and-push-oci-cli-image.yml'
    branches: [ "main" ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'oracle/oci-cli'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          labels: |
            provider=Oracle
            issues=https://github.com/oracle/docker-images/issues
            org.opencontainers.image.licenses=UPL-1.0
            org.opencontainers.image.vendor=Oracle
            org.opencontainers.image.title=OCI CLI
            org.opencontainers.image.description=Oracle Cloud Infrastructure Command Line Interface
            org.opencontainers.image.source=https://github.com/oracle/docker-images/tree/main/OracleCloudInfrastructure/oci-cli
            org.opencontainers.image.documentation=https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm
            org.opencontainers.image.url=https://github.com/oracle/docker-images/pkgs/container/oci-cli
            org.opencontainers.image.base.name=ghcr.io/oracle/oci-cli:latest
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha

      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./OracleCloudInfrastructure/oci-cli/
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
