cd#https://blog.pjjop.org/build-api-gateway-and-monitoring-microservice-with-kong-prometheus-and-grafana/
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" #SSL
    volumes:
      - vhost:/etc/nginx/vhost.d #SSL
      - html:/usr/share/nginx/html #SSL
      - certs:/etc/nginx/certs:ro #SSL
      - dhparam:/etc/nginx/dhparam #SSL
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt: #SSL
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
      
  kong:
    image: kong:2.0.2-alpine
    container_name: kong
    depends_on:
      - kong_db
      - kong_migration
      
    expose:
      - "8001"
      - "8444"
      - "8000"
      - "8443"
    restart: always
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong_db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          basic-auth, key-auth, rate-limiting, prometheus, proxy-cache, oauth2 , request-transformer , datadog

      VIRTUAL_HOST: kong.dev.docker
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: kong.dev.docker

    networks: 
    - proxy_network
    - default
    
  kong_db:
    image: postgres:9.6
    container_name: kong_db
    volumes:
      - kong_datastore:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_HOST_AUTH_METHOD: trust
  
  kong_migration:
    image: kong:latest
    container_name: kong_migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong_db
    depends_on:
      - kong_db
      
  konga:
    container_name: konga
    image: pantsel/konga
    restart: always

    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga_db
      DB_USER: konga 
      DB_DATABASE: konga
      NODE_ENV: development

      VIRTUAL_HOST: konga.dev.docker
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: konga.dev.docker

    expose:
    - "1337"
    depends_on:
      - konga_db
   

    networks: 
      - proxy_network
      - default
  
  konga_db:
    image: postgres:9.6
    container_name: konga_db
    volumes:
      - konga_database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: konga
      POSTGRES_USER: konga
      POSTGRES_HOST_AUTH_METHOD: trust 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - "9100"
    restart: always

volumes:
  kong_datastore:
  konga_database:
  prometheus_data:
  
networks:
  proxy_network:
    external:
      name: proxy_network
  #service_network:
  #  external:
  #    name: service_network            
  default:
    external:
      name: kong_network   # Create Network --> docker network create kong_network


---------------------
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" #SSL
    volumes:
      - vhost:/etc/nginx/vhost.d #SSL
      - html:/usr/share/nginx/html #SSL
      - certs:/etc/nginx/certs:ro #SSL
      - dhparam:/etc/nginx/dhparam #SSL
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt: #SSL
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
volumes: #SSL
  vhost:
  html:
  certs:
  dhparam:

networks:
  default:
    external:
      name:
        proxy_network      # Create Network --> docker network create proxy_network
       