# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MockupSendSocket.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from libs.bas_socket import socketSendData 
from datetime import datetime

#serverip = '192.168.1.37'
#port = 9008
#####################
buffsize = 1024 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 528)
        MainWindow.setMinimumSize(QtCore.QSize(368, 528))
        MainWindow.setMaximumSize(QtCore.QSize(368, 528))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 31, 16))
        self.label.setObjectName("label")
        self.txtIP = QtWidgets.QLineEdit(self.centralwidget)
        self.txtIP.setGeometry(QtCore.QRect(80, 50, 113, 22))
        self.txtIP.setObjectName("txtIP")
        self.txtPort = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPort.setGeometry(QtCore.QRect(200, 50, 41, 22))
        self.txtPort.setObjectName("txtPort")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_3.setObjectName("label_3")
        self.txtMsg = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMsg.setGeometry(QtCore.QRect(80, 90, 211, 22))
        self.txtMsg.setObjectName("txtMsg")
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(302, 90, 51, 28))
        self.btnSend.setObjectName("btnSend")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 120, 361, 321))
        self.groupBox.setObjectName("groupBox")
        self.lstResult = QtWidgets.QListView(self.groupBox)
        self.lstResult.setGeometry(QtCore.QRect(10, 20, 341, 291))
        self.lstResult.setObjectName("lstResult")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(130, 450, 93, 28))
        self.btnExit.setObjectName("btnExit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 0, 211, 31))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        #self.lblResult = QtWidgets.QLabel(self.centralwidget)
        #self.lblResult.setGeometry(QtCore.QRect(20, 70, 311, 16))
        #self.lblResult.setText("")
        #self.lblResult.setObjectName("lblResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.txtIP.setText('192.168.1.37')
        self.txtPort.setText('9008')
        self.txtMsg.setText('อุณหภูมิ:15|ความชื้น:25')
        #self.lblResult.setText('')

        self.model = QtGui.QStandardItemModel()
        self.lstResult.setModel(self.model)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MockupSendSocket"))
        self.label.setText(_translate("MainWindow", "IP :"))
        self.label_3.setText(_translate("MainWindow", "Message  :"))
        self.btnSend.setText(_translate("MainWindow", "Send"))
        self.groupBox.setTitle(_translate("MainWindow", "Result "))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Socket Send</span></p></body></html>"))
        self.btnSend.clicked.connect(self.sendSocket) 

    def sendSocket(self):
        serverip = self.txtIP.text()
        port = int(self.txtPort.text())
        msg = self.txtMsg.text() 
        resultServer =socketSendData(serverip,port,msg) 

        dt1 = datetime.now()
        date_time1 = dt1.strftime("%m/%d/%Y %H:%M:%S")
        strResult1 = '{} : Message {}'.format(date_time1,msg)
        # Add Result to List
        item = QtGui.QStandardItem(strResult1)
        self.model.appendRow(item) 

        dt2 = datetime.now()
        date_time2 = dt1.strftime("%m/%d/%Y %H:%M:%S")
        strResult2 = '{} : {}'.format(date_time2 ,resultServer) 
        # Add Result to List
        item = QtGui.QStandardItem(strResult2)
        self.model.appendRow(item) 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
