#https://blog.pjjop.org/how-to-config-vps-and-letsencrypt-with-docker-container/
#C:\Windows\System32\drivers\etc\hosts
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443" #SSL
    volumes:
      - vhost:/etc/nginx/vhost.d #SSL
      - html:/usr/share/nginx/html #SSL
      - certs:/etc/nginx/certs:ro #SSL
      - dhparam:/etc/nginx/dhparam #SSL
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt: #SSL
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
volumes: #SSL
  vhost:
  html:
  certs:
  dhparam:

networks:
  default:
    external:
      name:
        proxy_network      # Create Network --> docker network create proxy_network
 